### ISSUE TITLE
request: randomly generate colors if param `count` is > number of colors passed to param `colors`

### ISSUE THREAD

**Issue by jalavosus** [TimMikeladze/reptiles.dev#4]
Specifically, only do this if both parameters are explicitly passed by the user, ie:

- `?colors=0b486b` -> only use Astronaut Blue, since `count` was not explicitly passed
- `?count=4&colors=0b486b` -> use Astronaut Blue _and_ randomly generate three extra colors

I can do up a PR for this if it's something which makes sense to add :) 

Love this project by the way, going to be using it in quite a few places.

**Comment by TimMikeladze** [comment]
This would be useful to have.

Thank you for the recent PRs and your interest in this project.
